import struct
import math
import os

def write_binary_stl(filename, triangles):
    """
    Writes a list of triangles to a Binary STL file.
    Each triangle in the list is a tuple/list of:
    ( (nx, ny, nz), (v1x, v1y, v1z), (v2x, v2y, v2z), (v3x, v3y, v3z) )
    """
    with open(filename, 'wb') as f:
        # 80-byte header
        header = b'STL generated by AI Smart Car Assistant'.ljust(80, b'\0')
        f.write(header)
        
        # Number of triangles (4-byte uint)
        num_triangles = len(triangles)
        f.write(struct.pack('<I', num_triangles))
        
        # Write each triangle
        for tri in triangles:
            normal = tri[0]
            v1 = tri[1]
            v2 = tri[2]
            v3 = tri[3]
            
            # Pack normal and vertices (12 floats)
            data = struct.pack('<12f', 
                               normal[0], normal[1], normal[2],
                               v1[0], v1[1], v1[2],
                               v2[0], v2[1], v2[2],
                               v3[0], v3[1], v3[2])
            f.write(data)
            # Attribute byte count (2 bytes, set to 0)
            f.write(struct.pack('<H', 0))

def compute_normal(v1, v2, v3):
    """Computes the normal vector for a triangle."""
    ux = v2[0] - v1[0]
    uy = v2[1] - v1[1]
    uz = v2[2] - v1[2]
    
    vx = v3[0] - v1[0]
    vy = v3[1] - v1[1]
    vz = v3[2] - v1[2]
    
    # Cross product
    nx = uy * vz - uz * vy
    ny = uz * vx - ux * vz
    nz = ux * vy - uy * vx
    
    # Normalize
    length = math.sqrt(nx*nx + ny*ny + nz*nz)
    if length == 0:
        return (0.0, 0.0, 1.0)
    return (nx/length, ny/length, nz/length)

def add_quad(triangles, v1, v2, v3, v4):
    """Helper to add a quad (4 vertices) as 2 triangles, maintaining clockwise orientation."""
    n1 = compute_normal(v1, v2, v3)
    triangles.append((n1, v1, v2, v3))
    
    n2 = compute_normal(v1, v3, v4)
    triangles.append((n2, v1, v3, v4))

# -------------------------------------------------------------
# 1. GENERATE CHASSIS PLATE STL
# -------------------------------------------------------------
def generate_chassis_stl():
    print("Generating Chassis Plate STL...")
    # Dimensions in mm
    L = 160.0  # Length
    W = 100.0  # Width
    H = 4.0    # Thickness (Strong for 3D printing)
    
    triangles = []
    
    # 8 vertices of a simple solid block chassis
    v = [
        (0.0, 0.0, 0.0),  # 0
        (L, 0.0, 0.0),    # 1
        (L, W, 0.0),      # 2
        (0.0, W, 0.0),    # 3
        (0.0, 0.0, H),    # 4
        (L, 0.0, H),      # 5
        (L, W, H),        # 6
        (0.0, W, H)       # 7
    ]
    
    # Add 6 faces (each face is a quad = 2 triangles)
    # Bottom
    add_quad(triangles, v[0], v[3], v[2], v[1])
    # Top
    add_quad(triangles, v[4], v[5], v[6], v[7])
    # Front
    add_quad(triangles, v[0], v[1], v[5], v[4])
    # Back
    add_quad(triangles, v[2], v[3], v[7], v[6])
    # Left
    add_quad(triangles, v[0], v[4], v[7], v[3])
    # Right
    add_quad(triangles, v[1], v[2], v[6], v[5])
    
    write_binary_stl("chassis_plate.stl", triangles)
    print("Saved 'chassis_plate.stl' successfully!")

# -------------------------------------------------------------
# 2. GENERATE WHEEL STL (Cylinder with a central axle hole)
# -------------------------------------------------------------
def generate_wheel_stl():
    print("Generating Wheel STL...")
    # Dimensions in mm
    R = 35.0   # Radius (70mm diameter)
    W = 15.0   # Width
    r_axle = 2.7  # 5.4mm axle radius (fits standard TT motors)
    
    segments = 36  # Number of polygons to form the circle
    triangles = []
    
    # Generating vertices for outer cylinder and inner axle hole
    outer_bottom = []
    outer_top = []
    inner_bottom = []
    inner_top = []
    
    for i in range(segments):
        angle = 2.0 * math.pi * i / segments
        cos_a = math.cos(angle)
        sin_a = math.sin(angle)
        
        # Outer wheel rim vertices
        outer_bottom.append((R * cos_a, R * sin_a, 0.0))
        outer_top.append((R * cos_a, R * sin_a, W))
        
        # Inner axle hole vertices
        inner_bottom.append((r_axle * cos_a, r_axle * sin_a, 0.0))
        inner_top.append((r_axle * cos_a, r_axle * sin_a, W))

    # Add outer side wall faces
    for i in range(segments):
        next_i = (i + 1) % segments
        add_quad(triangles, outer_bottom[i], outer_bottom[next_i], outer_top[next_i], outer_top[i])
        
    # Add inner side wall faces (axle hole) - faces inward
    for i in range(segments):
        next_i = (i + 1) % segments
        add_quad(triangles, inner_bottom[i], inner_top[i], inner_top[next_i], inner_bottom[next_i])

    # Add bottom cap (Donut shape between inner and outer circles)
    for i in range(segments):
        next_i = (i + 1) % segments
        # Triangle 1
        v1 = outer_bottom[i]
        v2 = inner_bottom[i]
        v3 = inner_bottom[next_i]
        n1 = compute_normal(v1, v2, v3)
        triangles.append((n1, v1, v2, v3))
        
        # Triangle 2
        v4 = outer_bottom[i]
        v5 = inner_bottom[next_i]
        v6 = outer_bottom[next_i]
        n2 = compute_normal(v4, v5, v6)
        triangles.append((n2, v4, v5, v6))

    # Add top cap (Donut shape)
    for i in range(segments):
        next_i = (i + 1) % segments
        # Triangle 1
        v1 = outer_top[i]
        v2 = outer_top[next_i]
        v3 = inner_top[next_i]
        n1 = compute_normal(v1, v2, v3)
        triangles.append((n1, v1, v2, v3))
        
        # Triangle 2
        v4 = outer_top[i]
        v5 = inner_top[next_i]
        v6 = inner_top[i]
        n2 = compute_normal(v4, v5, v6)
        triangles.append((n2, v4, v5, v6))

    write_binary_stl("wheel.stl", triangles)
    print("Saved 'wheel.stl' successfully!")

# Run generators
if __name__ == "__main__":
    generate_chassis_stl()
    generate_wheel_stl()
    print("\nAll 3D STL files created! You can now load them into Bambu Studio.")
